"""Mock data for the analyst control plane (Segment 2).

Segment 1 treats the analyst as a *consumer* who might occasionally want SQL. This module
backs the opposite framing: the analyst as **producer** — the person who owns metric
definitions, triages what the copilot got wrong, and audits what it told the business.

Everything here stands in for tables the real build would own: a metric registry with
certification state, a feedback/telemetry store, and an audit log.
"""

import hashlib
from datetime import datetime, timedelta

import pandas as pd

import mock_data as md

# --- Metric registry ----------------------------------------------------------------
# The semantic layer as a *governed asset*: each definition has an owner, a certification
# state, and usage. This is what makes an analyst's work leveraged — one definition
# answers hundreds of questions instead of one ticket answering one.

CERTIFIED = "certified"
DRAFT = "draft"
DEPRECATED = "deprecated"

REGISTRY = {
    "conversion_rate": {
        "owner": "M. Okonjo · Marketplace Analytics",
        "status": CERTIFIED,
        "reviewed_days_ago": 12,
        "questions_7d": 96,
        "thumbs_down": 3,
        "definition": "Bookings ÷ sessions, by market and day. Excludes internal traffic "
        "and bot sessions. Denominator is sessions, not users.",
        "synonyms": ["conversion", "cvr", "booking rate"],
    },
    "gross_bookings": {
        "owner": "M. Okonjo · Marketplace Analytics",
        "status": CERTIFIED,
        "reviewed_days_ago": 12,
        "questions_7d": 74,
        "thumbs_down": 1,
        "definition": "Sum of booking value in USD at time of booking. Gross of "
        "cancellations — see cancellation_rate for net.",
        "synonyms": ["bookings", "gmv", "gross merchandise value"],
    },
    "adr": {
        "owner": "P. Lindqvist · Supply Analytics",
        "status": CERTIFIED,
        "reviewed_days_ago": 30,
        "questions_7d": 41,
        "thumbs_down": 0,
        "definition": "Average nightly rate in USD across booked room-nights. Excludes "
        "taxes and fees.",
        "synonyms": ["average daily rate", "nightly rate"],
    },
    "cancellation_rate": {
        "owner": "P. Lindqvist · Supply Analytics",
        "status": CERTIFIED,
        "reviewed_days_ago": 30,
        "questions_7d": 33,
        "thumbs_down": 0,
        "definition": "Cancelled bookings ÷ total bookings, by booking date (not "
        "cancellation date).",
        "synonyms": ["cancellations", "cancel rate"],
    },
    "marketing_roas": {
        "owner": "S. Devarajan · Marketing Analytics",
        "status": CERTIFIED,
        "reviewed_days_ago": 5,
        "questions_7d": 28,
        "thumbs_down": 2,
        "definition": "Gross bookings ÷ paid media spend, same market and day. Uses "
        "last-touch attribution.",
        "synonyms": ["roas", "return on ad spend"],
    },
    "marketing_spend": {
        "owner": "S. Devarajan · Marketing Analytics",
        "status": CERTIFIED,
        "reviewed_days_ago": 5,
        "questions_7d": 22,
        "thumbs_down": 0,
        "definition": "Paid media spend in USD by market and day, all channels.",
        "synonyms": ["spend", "media spend", "paid search spend"],
    },
    "csat": {
        "owner": "unassigned",
        "status": DRAFT,
        "reviewed_days_ago": 96,
        "questions_7d": 31,
        "thumbs_down": 6,
        "definition": "Mean CSAT score on resolved support tickets. **Draft** — grain is "
        "ambiguous between ticket date and resolution date, and the two disagree by ~4%.",
        "synonyms": ["satisfaction", "customer satisfaction"],
    },
    "support_tickets": {
        "owner": "unassigned",
        "status": DRAFT,
        "reviewed_days_ago": 96,
        "questions_7d": 19,
        "thumbs_down": 2,
        "definition": "Count of support tickets created, by market and day. **Draft** — "
        "does not yet exclude duplicate contacts on the same booking.",
        "synonyms": ["tickets", "contacts", "support volume"],
    },
}

# --- Feedback queue -----------------------------------------------------------------
# The analyst's work queue, generated by real usage. Note that not every row is a defect:
# triage includes confirming the product was right to refuse.

NO_MATCH = "no match"
REFUSED_PII = "refused · PII"
REFUSED_POLICY = "refused · role policy"
LOW_RATED = "thumbs down"

FEEDBACK_QUEUE = [
    {
        "id": "fb-01",
        "question": "What's our refund exposure in EMEA?",
        "outcome": NO_MATCH,
        "asks_30d": 14,
        "asked_by": "Exec, Market Manager",
        "diagnosis": "No `refund_exposure` metric exists. Refunds live in "
        "`fact_refunds`, which is not in the semantic layer at all.",
        "suggested": "Define a new metric",
        "severity": "high",
    },
    {
        "id": "fb-02",
        "question": "How is RevPAR trending in Paris?",
        "outcome": NO_MATCH,
        "asks_30d": 11,
        "asked_by": "Market Manager",
        "diagnosis": "RevPAR is derivable from existing fields (ADR × occupancy) but has "
        "no definition, so the copilot correctly refused to improvise one.",
        "suggested": "Define a new metric",
        "severity": "high",
    },
    {
        "id": "fb-03",
        "question": "Bookings by loyalty tier",
        "outcome": NO_MATCH,
        "asks_30d": 8,
        "asked_by": "Exec, Marketing",
        "diagnosis": "`dim_customer.loyalty_tier` exists in the warehouse but is not "
        "exposed as a dimension in the semantic layer.",
        "suggested": "Expose a dimension",
        "severity": "medium",
    },
    {
        "id": "fb-04",
        "question": "What's my ROAS this week?",
        "outcome": REFUSED_POLICY,
        "asks_30d": 9,
        "asked_by": "Partner Success",
        "diagnosis": "Partner Success is not entitled to marketing spend, so ROAS is "
        "refused. Nine asks in 30 days suggests the policy, not the product, is the "
        "question — do partner leads legitimately need spend efficiency?",
        "suggested": "Escalate policy review",
        "severity": "medium",
    },
    {
        "id": "fb-05",
        "question": "Why did conversion drop in Rome?",
        "outcome": LOW_RATED,
        "asks_30d": 27,
        "asked_by": "Market Manager",
        "diagnosis": "3 of 27 answers rated down. The driver attribution names the spend "
        "cut but does not test for a confound — Rome also had a 4-day platform incident "
        "in the same window.",
        "suggested": "Improve answer quality",
        "severity": "high",
    },
    {
        "id": "fb-06",
        "question": "Show me traveller email addresses for cancelled bookings",
        "outcome": REFUSED_PII,
        "asks_30d": 6,
        "asked_by": "Market Manager, Partner Success",
        "diagnosis": "Refused correctly — PII is blocked for every role. Repeat asks "
        "indicate a workflow gap, not a product defect: these users need the Traveler "
        "Support console and may not know it exists.",
        "suggested": "No change — working as intended",
        "severity": "low",
    },
    {
        "id": "fb-07",
        "question": "CSAT by market last quarter",
        "outcome": LOW_RATED,
        "asks_30d": 18,
        "asked_by": "Partner Success, Exec",
        "diagnosis": "6 thumbs-down on a draft metric. CSAT grain is ambiguous between "
        "ticket-created and ticket-resolved date; the two differ by ~4%, so two teams get "
        "different numbers for the same question.",
        "suggested": "Certify the definition",
        "severity": "high",
    },
]


# --- Audit log ----------------------------------------------------------------------
# What the copilot told the business, so an analyst can answer "is that number right?"

_AUDIT_SEED = [
    ("Market Manager", "Why did conversion drop in Rome?", "conversion_rate", 0.78, 90),
    ("Exec", "How are gross bookings trending this week?", "gross_bookings", 0.91, 5),
    ("Market Manager", "How is ADR trending in Rome?", "adr", 0.93, 90),
    ("Partner Success", "How is CSAT trending in Rome?", "csat", 0.93, 90),
    ("Exec", "How is marketing ROAS trending in Rome?", "marketing_roas", 0.93, 90),
    ("Market Manager", "Is the cancellation rate rising in Rome?", "cancellation_rate", 0.93, 90),
    ("Partner Success", "What's my ROAS this week?", None, 1.00, 0),
    ("Analyst", "How is marketing spend trending in Rome?", "marketing_spend", 0.93, 90),
    ("Market Manager", "What's our refund exposure in EMEA?", None, 0.20, 0),
    ("Exec", "How is CSAT trending in London?", "csat", 0.93, 90),
    ("Partner Success", "Are support tickets rising in Rome?", "support_tickets", 0.93, 90),
    ("Market Manager", "Show me traveller email addresses", None, 1.00, 0),
]


def audit_log() -> pd.DataFrame:
    """Recent copilot answers, newest first."""
    now = datetime.now().replace(second=0, microsecond=0)
    rows = []
    for i, (role, question, metric, conf, rows_returned) in enumerate(_AUDIT_SEED):
        # Deterministic but irregular spacing, so it reads like real traffic.
        gap = 17 + (int(hashlib.md5(question.encode()).hexdigest()[:2], 16) % 43)
        rows.append(
            {
                "when": now - timedelta(minutes=gap * (i + 1)),
                "role": role,
                "question": question,
                "metric": metric or "—",
                "outcome": "answered" if metric else ("refused" if conf >= 0.99 else "no match"),
                "confidence": conf,
                "rows": rows_returned,
            }
        )
    return pd.DataFrame(rows)


def sql_for(metric_id):
    if not metric_id or metric_id == "—":
        return None
    return md.METRICS[metric_id]["sql"]


def coverage_stats(open_issues: int) -> dict:
    answered = sum(1 for r in _AUDIT_SEED if r[2])
    return {
        "coverage_pct": round(answered / len(_AUDIT_SEED) * 100),
        "questions_7d": sum(m["questions_7d"] for m in REGISTRY.values()),
        "certified": sum(1 for m in REGISTRY.values() if m["status"] == CERTIFIED),
        "total_metrics": len(REGISTRY),
        "open_issues": open_issues,
    }
