"""Analyst control plane — Segment 2.

The analyst's value here is not asking questions faster. It is owning the semantic layer
that answers everyone else's: certifying definitions, triaging what the copilot got wrong,
and auditing what it told the business. Their job shifts from answering questions to
making the system able to answer them.

Three surfaces, one per job:
  1. Feedback queue — what usage says is broken or missing
  2. Metric catalog — the governed definitions they own
  3. Audit log     — what the copilot actually told people
"""

import streamlit as st

import analyst_data as ad
import eval_data as ev
import evidence_data as ed
import feedback_store as fs
import mock_data as md

STATUS_STYLE = {
    ad.CERTIFIED: ("✓ certified", "pill-ok"),
    ad.DRAFT: ("◐ draft", "pill-warn"),
    ad.DEPRECATED: ("⊘ deprecated", "pill-muted"),
}

SEVERITY_STYLE = {"high": "pill-warn", "medium": "pill", "low": "pill-muted"}


def _state():
    st.session_state.setdefault("cp_resolved", set())
    st.session_state.setdefault("cp_status", {})
    return st.session_state["cp_resolved"], st.session_state["cp_status"]


def status_of(metric_id: str) -> str:
    _, overrides = _state()
    return overrides.get(metric_id, ad.REGISTRY[metric_id]["status"])


# --- 1. Feedback queue --------------------------------------------------------------

def render_feedback_queue() -> None:
    resolved, _ = _state()
    st.caption(
        "**What usage says is missing or wrong.** Generated by real questions — every row "
        "is work that makes the next hundred answers better, not one ticket for one person."
    )

    counts = fs.summary()
    if counts["down"]:
        st.markdown(
            f'<span class="pill pill-warn">{counts["down"]} rated down</span>'
            f'<span class="pill pill-ok">{counts["up"]} rated up</span>'
            f'<span class="pill pill-muted">{counts["detailed"]} gave a reason</span>',
            unsafe_allow_html=True,
        )

    # Live thumbs-down lead, grouped one row per question — a bad answer served to twenty
    # people is one fix, not twenty tickets. Seeded rows follow.
    all_items = (
        fs.queue_items() + ad.FEEDBACK_QUEUE + st.session_state.get("cp_added", [])
    )
    open_items = [f for f in all_items if f["id"] not in resolved]
    if not open_items:
        st.success("Queue clear. Every reported gap has been triaged.", icon="✅")
        return

    for item in open_items:
        with st.container(border=True):
            head, meta = st.columns([5, 2], vertical_alignment="center")
            with head:
                st.markdown(f"**{item['question']}**")
            with meta:
                st.markdown(
                    f'<div style="text-align:right">'
                    + ('<span class="pill pill-ok">live</span>' if item.get("live") else "")
                    + f'<span class="pill {SEVERITY_STYLE[item["severity"]]}">{item["outcome"]}</span>'
                    # Seeded rows count asks; a grouped thumbs-down row counts ratings.
                    # Labelling both "asks · 30d" would misreport the live ones.
                    f'<span class="pill pill-muted">{item["asks_30d"]} '
                    f'{item.get("count_label", "asks · 30d")}</span></div>',
                    unsafe_allow_html=True,
                )

            st.markdown(
                f'<span class="cp-label">Asked by</span> {item["asked_by"]}',
                unsafe_allow_html=True,
            )
            st.markdown(
                f'<span class="cp-label">Diagnosis</span> {item["diagnosis"]}',
                unsafe_allow_html=True,
            )

            act, dismiss, _ = st.columns([2.4, 1.4, 4])
            if act.button(item["suggested"], key=f"act_{item['id']}", width="stretch",
                          type="primary" if item["severity"] == "high" else "secondary"):
                resolved.add(item["id"])
                st.toast(f"{item['suggested']} → queued for {item['question'][:30]}…", icon="🛠")
                st.rerun()
            if dismiss.button("Dismiss", key=f"dis_{item['id']}", width="stretch",
                              type="tertiary"):
                resolved.add(item["id"])
                st.rerun()


# --- 2. Metric catalog --------------------------------------------------------------

def render_catalog() -> None:
    _, overrides = _state()
    st.caption(
        "**The definitions you own.** One certified definition serves every surface, which "
        "is what kills reconciliation work — the exec dashboard and your query can no "
        "longer disagree."
    )

    for metric_id, meta in ad.REGISTRY.items():
        spec = md.METRICS[metric_id]
        status = status_of(metric_id)
        label, css = STATUS_STYLE[status]

        with st.container(border=True):
            head, badge = st.columns([5, 2], vertical_alignment="center")
            with head:
                st.markdown(f"**{spec['label']}**  `{metric_id}`")
            with badge:
                st.markdown(
                    f'<div style="text-align:right"><span class="pill {css}">{label}</span></div>',
                    unsafe_allow_html=True,
                )

            st.markdown(meta["definition"])
            st.markdown(
                f'<span class="cp-label">Owner</span> {meta["owner"]} &nbsp; '
                f'<span class="cp-label">Sources</span> '
                f'<code>{"</code>, <code>".join(spec["lineage"])}</code>',
                unsafe_allow_html=True,
            )
            st.markdown(
                f'<span class="cp-label">Usage</span> {meta["questions_7d"]} questions · 7d '
                f'&nbsp; <span class="cp-label">Rated down</span> {meta["thumbs_down"]} '
                f'&nbsp; <span class="cp-label">Reviewed</span> '
                f'{meta["reviewed_days_ago"]}d ago '
                f'&nbsp; <span class="cp-label">Synonyms</span> '
                f'{", ".join(meta["synonyms"])}',
                unsafe_allow_html=True,
            )

            if status == ad.DRAFT:
                st.warning(
                    f"Draft definitions still answer questions — {meta['questions_7d']} in "
                    "the last 7 days. Until certified, two teams can get different numbers "
                    "for the same question.",
                    icon="⚠️",
                )

            c1, c2, _ = st.columns([1.6, 1.6, 5])
            if status != ad.CERTIFIED:
                if c1.button("✓ Certify", key=f"cert_{metric_id}", width="stretch",
                             type="primary"):
                    overrides[metric_id] = ad.CERTIFIED
                    st.toast(f"{spec['label']} certified", icon="✅")
                    st.rerun()
            else:
                if c1.button("Edit definition", key=f"edit_{metric_id}", width="stretch",
                             type="tertiary"):
                    st.toast("Definition editing is mocked in this prototype", icon="✏️")
            if c2.button("⊘ Deprecate", key=f"dep_{metric_id}", width="stretch",
                         type="tertiary"):
                overrides[metric_id] = ad.DEPRECATED
                st.rerun()


# --- 3. Evaluation harness ----------------------------------------------------------

def render_quality() -> None:
    s = ev.summary()
    st.caption(
        f"**{int(s['sample_rate']*100)}% of live answers are sampled and scored by a judge "
        f"model** on whether they were grounded, calibrated, and helpful. This is a read on "
        "production, not a test suite — and a failing row is only useful if it becomes work, "
        "so each one can be sent to the queue."
    )

    k1, k2, k3, k4 = st.columns(4)
    k1.metric("Mean score", f"{s['mean_score']}/5")
    k2.metric("Pass rate", f"{s['pass_rate']}%")
    k3.metric("Sampled · 7d", f"{s['shown']} of {s['sampled']}",
              help=f"{s['sample_rate']:.0%} of {s['traces_7d']:,} answers")
    k4.metric("Failing", s["failing"], delta="needs review" if s["failing"] else None,
              delta_color="inverse")

    st.markdown(
        " ".join(
            f'<span class="pill pill-muted">{d}: {v}</span>'
            for d, v in s["by_dimension"].items()
        ),
        unsafe_allow_html=True,
    )

    weakest = ev.by_metric().iloc[0]
    st.info(
        f"Weakest definition: **{md.METRICS[weakest['metric']]['label']}** at "
        f"{weakest['mean_score']}/5 across {int(weakest['traces'])} sampled answers "
        f"(calibration {weakest['calibrated']}/5). Low calibration usually means the "
        "definition is ambiguous, not that the model is wrong.",
        icon="🔍",
    )

    df = ev.traces()
    st.dataframe(
        df[["mins_ago", "role", "question", "metric", "design",
            "grounded", "calibrated", "helpful", "verdict"]],
        width="stretch",
        hide_index=True,
        column_config={
            "mins_ago": st.column_config.NumberColumn("Mins ago", width="small"),
            "role": st.column_config.TextColumn("Asked by"),
            "question": st.column_config.TextColumn("Question", width="large"),
            "metric": st.column_config.TextColumn("Metric"),
            "design": st.column_config.TextColumn("Evidence"),
            "grounded": st.column_config.ProgressColumn(
                "Grounded", min_value=0, max_value=5, format="%d"),
            "calibrated": st.column_config.ProgressColumn(
                "Calibrated", min_value=0, max_value=5, format="%d"),
            "helpful": st.column_config.ProgressColumn(
                "Helpful", min_value=0, max_value=5, format="%d"),
            "verdict": st.column_config.TextColumn("Verdict"),
        },
    )

    st.markdown("**Low-scoring answers**")
    resolved, _ = _state()
    weak = df[df["verdict"] != "pass"]
    for _, r in weak.iterrows():
        key = f"ev_{r['id']}"
        if key in resolved:
            continue
        with st.container(border=True):
            st.markdown(f"**{r['question']}** · {r['role']}")
            st.markdown(
                f'<span class="pill pill-warn">{r["verdict"]}</span>'
                f'<span class="pill pill-muted">grounded {r["grounded"]} · '
                f'calibrated {r["calibrated"]} · helpful {r["helpful"]}</span>',
                unsafe_allow_html=True,
            )
            st.markdown(f'<span class="cp-label">Judge</span> {r["note"]}',
                        unsafe_allow_html=True)
            c1, c2, _ = st.columns([2, 1.3, 4])
            if c1.button("Send to queue", key=f"toq_{r['id']}", width="stretch",
                         type="primary"):
                st.session_state.setdefault("cp_added", []).append(
                    {
                        # Distinct from `key`: `key` marks the eval row handled, and
                        # reusing it would make the queue filter hide the new item.
                        "id": f"q_{key}",
                        "question": r["question"],
                        "outcome": "low judge score",
                        "asks_30d": 1,
                        "asked_by": r["role"],
                        "diagnosis": r["note"],
                        "suggested": "Certify the definition"
                        if r["metric"] != "—"
                        else "Improve answer quality",
                        "severity": "high" if r["verdict"] == "fail" else "medium",
                    }
                )
                resolved.add(key)
                st.toast("Added to the feedback queue", icon="📋")
                st.rerun()
            if c2.button("Dismiss", key=f"evdis_{r['id']}", width="stretch", type="tertiary"):
                resolved.add(key)
                st.rerun()

    st.caption(
        "⚠️ The judge is a model too. Before these scores drive decisions they need "
        "calibrating against a human-labelled sample — otherwise you are measuring "
        "agreement with a model, not quality."
    )


# --- 4. Experiments -----------------------------------------------------------------

def render_experiments() -> None:
    st.caption(
        "**Read-only mirror of the experimentation platform.** We never recompute their "
        "statistics — we join their scorecards to our metrics by `metric_id`. That join is "
        "the point: an experiment and a dashboard disagreeing about \"conversion rate\" is "
        "the reconciliation work this product exists to delete."
    )

    uncertified = [
        e for e in ed.EXPERIMENTS if status_of(e["metric_id"]) != ad.CERTIFIED
    ]
    if uncertified:
        st.warning(
            f"**{len(uncertified)} experiment(s) are measuring an uncertified metric.** "
            "A shipping decision resting on a draft definition is a governance risk — "
            "certify it or stop the test.",
            icon="⚠️",
        )

    for e in ed.EXPERIMENTS:
        spec = md.METRICS[e["metric_id"]]
        cert = status_of(e["metric_id"])
        cert_label, cert_css = STATUS_STYLE[cert]

        with st.container(border=True):
            head, badge = st.columns([5, 2], vertical_alignment="center")
            with head:
                st.markdown(f"**{e['name']}**  `{e['experiment_id']}`")
            with badge:
                srm = (
                    '<span class="pill pill-warn">SRM fail</span>'
                    if not e["srm_pass"]
                    else '<span class="pill pill-ok">SRM ok</span>'
                )
                st.markdown(
                    f'<div style="text-align:right">{srm}'
                    f'<span class="pill pill-muted">{e["status"]}</span></div>',
                    unsafe_allow_html=True,
                )

            st.markdown(f"_{e['hypothesis']}_")

            if e["srm_pass"]:
                lo, hi = e["ci"]
                sig = "significant" if e["p_value"] < 0.05 else "not conclusive"
                st.markdown(
                    f"**{e['estimate']:+.1f}%** on {spec['label']} · "
                    f"95% CI [{lo:+.1f}, {hi:+.1f}] · p={e['p_value']:.3f} — _{sig}_"
                )
            else:
                st.error(
                    "Sample ratio mismatch — the observed allocation differs from the "
                    "design. No effect can be read from this experiment at all.",
                    icon="🚫",
                )

            st.markdown(
                f'<span class="cp-label">Metric</span> `{e["metric_id"]}` '
                f'<span class="pill {cert_css}">{cert_label}</span> &nbsp; '
                f'<span class="cp-label">Market</span> {e["market"]} &nbsp; '
                f'<span class="cp-label">Unit</span> {e["unit"]} &nbsp; '
                f'<span class="cp-label">Exposed</span> {e["exposed_users"]:,} &nbsp; '
                f'<span class="cp-label">Decision</span> {e["decision"]}',
                unsafe_allow_html=True,
            )

            if cert != ad.CERTIFIED:
                st.caption(
                    f"⚠️ This experiment is measuring a **{cert}** definition. Certify "
                    f"{spec['label']} in the catalog before acting on this readout."
                )


# --- 4. Audit log -------------------------------------------------------------------

def render_audit() -> None:
    st.caption(
        "**What the copilot told the business.** When a market manager asks you to check a "
        "number they were given, this is where you answer it — the exact question, query, "
        "and confidence behind their answer."
    )

    df = ad.audit_log()
    st.dataframe(
        df,
        width="stretch",
        hide_index=True,
        column_config={
            "when": st.column_config.DatetimeColumn("When", format="MMM DD, HH:mm"),
            "role": st.column_config.TextColumn("Asked by"),
            "question": st.column_config.TextColumn("Question", width="large"),
            "metric": st.column_config.TextColumn("Metric"),
            "outcome": st.column_config.TextColumn("Outcome"),
            "confidence": st.column_config.ProgressColumn(
                "Confidence", min_value=0.0, max_value=1.0, format="%.2f"
            ),
            "rows": st.column_config.NumberColumn("Rows"),
        },
    )

    st.markdown("**Inspect an answer**")
    options = list(range(len(df)))
    idx = st.selectbox(
        "Entry",
        options,
        format_func=lambda i: f"{df.iloc[i]['when']:%b %d, %H:%M} · {df.iloc[i]['role']} · "
        f"{df.iloc[i]['question']}",
        label_visibility="collapsed",
    )
    row = df.iloc[idx]
    sql = ad.sql_for(row["metric"])
    if sql:
        st.code(sql, language="sql")
        st.caption(
            f"Sources: `{'`, `'.join(md.METRICS[row['metric']]['lineage'])}` · "
            f"returned {row['rows']} rows · confidence {row['confidence']:.0%}"
        )
    else:
        st.info(
            f"No query ran — outcome was **{row['outcome']}**. Nothing was executed against "
            "the warehouse, so there is no result to audit.",
            icon="🔒",
        )


# --- Shell --------------------------------------------------------------------------

def render() -> None:
    resolved, _ = _state()
    queue_items = ad.FEEDBACK_QUEUE + st.session_state.get("cp_added", [])
    open_issues = len([f for f in queue_items if f["id"] not in resolved])
    stats = ad.coverage_stats(open_issues)
    certified_now = sum(1 for m in ad.REGISTRY if status_of(m) == ad.CERTIFIED)

    st.markdown('<div class="panel-title">🛠 Control Plane</div>', unsafe_allow_html=True)
    st.caption(
        "You are not a user of the copilot here — you are its supply side. Every definition "
        "you certify and every gap you close answers questions you will never see."
    )

    k1, k2, k3, k4 = st.columns(4)
    k1.metric("Answer coverage", f"{stats['coverage_pct']}%",
              help="Share of recent questions answered rather than refused or unmatched")
    k2.metric("Questions · 7d", f"{stats['questions_7d']}")
    k3.metric("Certified metrics", f"{certified_now}/{stats['total_metrics']}")
    k4.metric("Open issues", stats["open_issues"],
              delta=None if not stats["open_issues"] else "needs triage",
              delta_color="inverse")

    st.divider()

    tab_queue, tab_quality, tab_catalog, tab_exp, tab_audit = st.tabs(
        [f"⚑  Feedback queue ({open_issues})", "📈  Evaluation Harness",
         "📖  Metric catalog", "🧪  Experiments", "🔍  Audit log"]
    )
    with tab_queue:
        render_feedback_queue()
    with tab_quality:
        render_quality()
    with tab_catalog:
        render_catalog()
    with tab_exp:
        render_experiments()
    with tab_audit:
        render_audit()
